### PR TITLE
Remove allowBackup & supportsRtl from lib manifest

### LINKED ISSUE #18: Library manifest shouldn't define supportsRtl and allowBackup
Hi,

In a project where I intentionally set `android:allowBackup="false"` in the `<application .../>` tag of my manifest, and it clashes with this library, because it's defined [here](https://github.com/metalabdesign/AsyncAwait/blob/06d2f3389d941d5f92ae63f735c3ce80bd320837/asyncawait/src/main/AndroidManifest.xml#L5). These attributes should be removed.

### PR DESCRIPTION
**Pull request by LouisCAD**
Fixes #18

### CODE REVIEW

**Comment by pilgr** [comment]
@LouisCAD thanks, we're just getting a [CLA](https://en.wikipedia.org/wiki/Contributor_License_Agreement) and then we can merge your changes 👍

**Comment by LouisCAD** [comment]
@pilgr Is a CLA really necessary to contribute to an open source repo under the Apache 2 license?

**Comment by pilgr** [comment]
@LouisCAD unfortunately - yes, it's a necessary legal part to transfer the right for your contribution. It should be as easy for you as one click on the link https://cla-assistant.io/metalabdesign/AsyncAwait?pullRequest=19. The link is also available at the `All checks` section for this PR. Thank you!

**Comment by pilgr** [comment]
@LouisCAD could you accept CLA by the link above? So we can merge the PR. Thanks!

**Comment by LouisCAD** [comment]
@pilgr I already signed it, GitHub says checks have passed

**Comment by pilgr** [comment]
@LouisCAD oops, my fault, didn't get notification that it happened, thanks!

**Pull request merged**
